### ISSUE TITLE
Flux RSS

### ISSUE THREAD

**Issue by ThibaudDauce** [vjousse/lucky-blog#1]
Il me semble que le flux RSS de ton blog a disparu suite à la refonte, non ?

Merci pour les articles de qualité :-)

**Comment by vjousse** [comment]
J'ai oublié de remettre le lien mais normalement celui-ci devrait toujours fonctionner non ? https://vincent.jousse.org/rss.xml

**Comment by ThibaudDauce** [comment]
Effectivement il est toujours présent mais les liens ne sont que des 404 à l'intérieur. Par exemple https://vincent.jousse.org/articles/adding-tailwindcss-to-lucky-crystal-lang, je pense que le schéma des URL a un peu changé, non ?

**Comment by vjousse** [comment]
Bien vu ! Ça devrait être corrigé, tu peux vérifier ?

**Comment by ThibaudDauce** [comment]
Oui c'est bon ça refonctionne ! Merci !
